### ISSUE TITLE
Thanks!!!

### ISSUE THREAD

**Issue by kcifuentes** [rodrigogs/ilsap#11]
It's amazing, i were like 5 months with this inconvenient and i didnt find how to solve it, thanks for the help!

**Comment by boomsya** [comment]
I will try to make PHP version of this active proxy because I have a local web server on XAMPP

anyway thanks :)

**Comment by boomsya** [comment]
or you can use https://github.com/mitmproxy/mitmproxy/releases

mitmproxy -p 1017 -R http://xidea.online
