### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [rodrigogs/ilsap#13]
When I run the command

sudo npm install ilsap -g

It's giving me below error.

![screenshot from 2018-01-27 15-10-31](https://user-images.githubusercontent.com/10863510/35470709-68638d36-0374-11e8-980a-99dd47feff5f.png)

**Comment by sawankumarbundelkhandi** [comment]
@igorKryvenko It's also not working

![image](https://user-images.githubusercontent.com/10863510/35471553-202b3802-0383-11e8-8434-56a0b7b101fa.png)

**Comment by mycodeself** [comment]
Same here. I tried with previous version (1.2.0) and can install it, but the i get error when the proxy makes the request. 

Here the error:
`Redirecting...
Request error { Error: getaddrinfo ENOTFOUND rpc rpc:80
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rpc',
  host: 'rpc',
  port: 80 }
`
Maybe intellij its blocking it...

**Comment by igorKryvenko** [comment]
@sawankumarbundelkhandi Today i tried Intellij Idea 2017.3, it wan's working. Then  i tried without `-g` and   it installed.

**Comment by rodrigogs** [comment]
I'll try to fix it tonight. I think it happens due to ngrock dependency that I added.

I think I'll just remove it.

**Comment by rodrigogs** [comment]
This should be resolved in version 2.1.0. I just removed ngrok option as it seems not that usefull, and the lib has installation problems for some platforms.

Thanks for the information!
