### ISSUE TITLE
Cannot obtain ticket from http://127.0.0.1:8997 due to connectivity problem

### ISSUE THREAD

**Issue by lousaibiao** [rodrigogs/ilsap#4]
![1](https://user-images.githubusercontent.com/5031223/34815932-39d77564-f6ee-11e7-9193-4607538a1b36.jpg)

**Comment by ashofthephoenix** [comment]
+1

**Comment by rodrigogs** [comment]
Try the alternative license servers using the -s or --server option: https://github.com/rodrigogs/ilsap#alternative-license-servers

Let me know if it works.

**Comment by rodrigogs** [comment]
It seems there is no free license servers available for Rider.

**Comment by ashofthephoenix** [comment]
idea.ibdyr.com worked for me for quite some time, so i used it with this package. no success

**Comment by rodrigogs** [comment]
Thanks, I added idea.ibdyr.com to the alternative servers.

**Comment by rodrigogs** [comment]
@lousaibiao try again with the latest version. Please, let me know if it works now.

**Comment by lousaibiao** [comment]
@rodrigogs works for me after update ilsap version by 
`$ npm install ilsap -g`
then use server "http://idea.ibdyr.com"

**Comment by rodrigogs** [comment]
Thank you for the feedback ;)
