### ISSUE TITLE
 Error: getaddrinfo ENOTFOUND rpc rpc:80

### ISSUE THREAD

**Issue by ianitsky** [rodrigogs/ilsap#8]
$ ilsap
Starting server...
Listening on http://0.0.0.0:8997 <- Use this url to register your product
Redirecting requests to http://xidea.online
Redirecting...
Request error { Error: getaddrinfo ENOTFOUND rpc rpc:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rpc',
  host: 'rpc',
  port: 80 }

**Comment by rodrigogs** [comment]
It seems your network is unable to reach http://xidea.online

Try the aternative servers: https://github.com/rodrigogs/ilsap#alternative-license-servers

**Comment by ianitsky** [comment]
I try all networks, and the only one that worked is:  http://idea.imsxm.com/

Thank you
